################## METADATA ##################
# NAME: Johan Olsson
# USERNAME: d15johol
# COURSE: IT341G
# ASSIGNMENT: Powershell 6.2
# DATE OF LAST CHANGE: 2016-03-15
##############################################

Set-StrictMode -Version Latest

$User = [System.Environment]::UserName

$StoredSum = [math]::Round(((Get-ChildItem "C:\Users\$User" -Recurse -Force -ErrorAction SilentlyContinue | Measure-Object -property length -sum | Select-Object -ExpandProperty Sum) / 1MB))

Echo "Stored Sum: $StoredSum MB"
# SIG # Begin signature block
# MIII0AYJKoZIhvcNAQcCoIIIwTCCCL0CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUE7q3O7eLOoOrPkiSQibe/1nj
# /z2gggYMMIIGCDCCBPCgAwIBAgITHAAAAATBj/RoFAEsggAAAAAABDANBgkqhkiG
# 9w0BAQ0FADB1MRIwEAYKCZImiZPyLGQBGRYCc2UxEzARBgoJkiaJk/IsZAEZFgNo
# aXMxEzARBgoJkiaJk/IsZAEZFgNuc2ExGTAXBgoJkiaJk/IsZAEZFglzY3JpcHRp
# bmcxGjAYBgNVBAMTEXNjcmlwdGluZy1EQzAxLUNBMB4XDTE2MDMxNTE0MjA1NloX
# DTE3MDMxNTE0MjA1NlowgYExEjAQBgoJkiaJk/IsZAEZFgJzZTETMBEGCgmSJomT
# 8ixkARkWA2hpczETMBEGCgmSJomT8ixkARkWA25zYTEZMBcGCgmSJomT8ixkARkW
# CXNjcmlwdGluZzEOMAwGA1UEAxMFVXNlcnMxFjAUBgNVBAMTDUFkbWluaXN0cmF0
# b3IwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCRQ9V0JinW5fx5x7v0
# Dtv0V54/mYeMSjZK4Enn1p0oiAuFIS2fO1bgcP9+zTx7n3nLrjpLJv2V/nnsY26J
# cCmPuiJ9dWVaZSvcE5Kr8D2ktzuGFPdkEowyfq7eiC6pYKyIG5bsMh4H7o9H5VAO
# QM0m8daFOBB36GlKvxQCyIW39cw+ok9LL6Pe5ioVSZGog1YLAre7jqCSUJUlGlDS
# gIMJENGBNUaNAKsREPgHD+3ZApyeWLOYO5KrALQ0zSM7Trt981GRb15AufJVnA/B
# XCEer0GLHumeohEkoodsPDIA/N4lcgwvSe9Ec4gzcOcQJdfRLK2PHor1brrRwJEC
# UTDlAgMBAAGjggKCMIICfjAlBgkrBgEEAYI3FAIEGB4WAEMAbwBkAGUAUwBpAGcA
# bgBpAG4AZzATBgNVHSUEDDAKBggrBgEFBQcDAzAOBgNVHQ8BAf8EBAMCB4AwHQYD
# VR0OBBYEFGvYzLQEUzUJv7FPnbzeWNAEzuDaMB8GA1UdIwQYMBaAFNfXV0diulFJ
# 39Pm9qLpse+0u9c/MIHbBgNVHR8EgdMwgdAwgc2ggcqggceGgcRsZGFwOi8vL0NO
# PXNjcmlwdGluZy1EQzAxLUNBLENOPURDMDEsQ049Q0RQLENOPVB1YmxpYyUyMEtl
# eSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9c2Ny
# aXB0aW5nLERDPW5zYSxEQz1oaXMsREM9c2U/Y2VydGlmaWNhdGVSZXZvY2F0aW9u
# TGlzdD9iYXNlP29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50MIHSBggr
# BgEFBQcBAQSBxTCBwjCBvwYIKwYBBQUHMAKGgbJsZGFwOi8vL0NOPXNjcmlwdGlu
# Zy1EQzAxLUNBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1T
# ZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXNjcmlwdGluZyxEQz1uc2EsREM9
# aGlzLERDPXNlP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZp
# Y2F0aW9uQXV0aG9yaXR5MD0GA1UdEQQ2MDSgMgYKKwYBBAGCNxQCA6AkDCJBZG1p
# bmlzdHJhdG9yQHNjcmlwdGluZy5uc2EuaGlzLnNlMA0GCSqGSIb3DQEBDQUAA4IB
# AQCr6fKkhf4q394CSVSGtLSuH4HeAizt8n+IfJEJyg7Ne1OLYhq3mIsDqgvV2osX
# 3IHMWUAw7lbvUfqXlauC8q8N+3ObavUS5VgYj4EDEjwUB42ISu6u7uLL5nAG3lhI
# CPy1TLLSJi7/gkSjNFtMhs/WzipzhSN7pAzn+r8eXnwgqUPmGseDtMVRJndmEKPQ
# yzkFkcNIm9h+on8ijOLX/5vMM7nQJOUVvYHdm/emIqXupYq4Deqjavum0NQu7Kw3
# FQ0HActn2WqDNd/Km2t6OKdNo+WwR7l9zsWuPKwCm2nCsInC+djWXymCDTPyE05X
# cITU/joLVPmPVmHz7Z2E72E4MYICLjCCAioCAQEwgYwwdTESMBAGCgmSJomT8ixk
# ARkWAnNlMRMwEQYKCZImiZPyLGQBGRYDaGlzMRMwEQYKCZImiZPyLGQBGRYDbnNh
# MRkwFwYKCZImiZPyLGQBGRYJc2NyaXB0aW5nMRowGAYDVQQDExFzY3JpcHRpbmct
# REMwMS1DQQITHAAAAATBj/RoFAEsggAAAAAABDAJBgUrDgMCGgUAoHgwGAYKKwYB
# BAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAc
# BgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUDa91
# GOf9faso3ktNPeRv7pID4QwwDQYJKoZIhvcNAQEBBQAEggEAjDI7ER55gu78s4g1
# A5+P7jUk1uIvnwWllmytOSf0/zCjbrYMrKDzsoNNP45Mrr6BHS8AJNSgbN+0SRbe
# 8TvZaQTJ3NKRgStBI6etSjswUHb/hLZB3m8flj4CdT3bwP6stwm1UJ5oU5W3ibs/
# P+ux+hNG+9td4Dv7vVXMJyQ2fkzV47GHUHbP2Kr+BmgX9qbiMfuollgy2YEFGQ7/
# 1MtankbFFs8R6HkULNyPXIH9fXvErK3XoPZqilT8vJLktBl/u5ZFcINwDxE3la5Y
# wnXeR0W/wq+1RBiDarrrrLlI80E4iwTHTUX+qe9alRT4EOGNpOKjlZ/C0BxjsaHR
# 1/n01g==
# SIG # End signature block
